// 389. Find the Difference

// Given two strings s and t which consist of only lowercase letters.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Find the letter that was added in t.

// Example:

// Input:
// s = "abcd"
// t = "abcde"

// Output:
// e

// Explanation:
// 'e' is the letter that was added.

#include <iostream>
#include <string>

using namespace std;


class Solution {
public:
    char findTheDifference(string s, string t) {
        if (t.length() > s.length())
        {
        	// 将每个字符映射到数组的下标中
        	int charMap[256] = {0};
        	for (int i = 0; i < t.length(); ++i)
        	{
        		// 将长字符串中的字符先加上
        		charMap[int(t[i])] += 1;

        		if (i < s.length())
        		{
        			// 如果存在相同的字符，那么对应值减去后应该为0
        			charMap[int(s[i])] -= 1;
        		}
        	}

        	for (int i = 0; i < 256; ++i)
        	{
        		// 非0的值的下标即为对应的字符
        		if (charMap[i] != 0)
        		{
        			return char(i);
        		}
        	}
        }
        return ' ';
    }
};

int main(void)
{
	Solution sl;

	string s = "abcdabcdabcd";
	string t = "abcdabdcdabcd";

	cout << sl.findTheDifference(s, t);
	return 0;
}